targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: app_recipes_managment|lib/app/data/graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: app_recipes_managment|lib/app/data/graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: app_recipes_managment|lib/app/data/graphql

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: app_recipes_managment|lib/app/data/graphql