name: app_recipes_managment
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  hasura_connect: ^2.0.1

dev_dependencies:
  ferry_generator: ^0.3.3
  build_runner: ^1.10.2
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true